### ISSUE TITLE
New AIs, scanning sample code and b68 output

### ISSUE THREAD

**Issue by GrupoWebex** [ayeo/gs1_128#12]
Helllo, thanks for your work. I have 3 questions to avoid.

I need 2 news AI:
===============
11 | Production date (YYMMDD) | n2+n6 | PROD DATE (i think is the same as (12))
21 | Serial number | n2+an..20 | SERIAL

Scanning the sample code 
===============
$salida= $builder->output('(415)7709998021938(8020)0000000583(3900)01243200(96)20170714');
produces... 415770999802138802000000058339000124300962017
should be?... 4157709998021[9]3880200000000583390001243[2]0096201707[14]
What happen with lost numbers? Is that normal? Is barcode working? Is not my scanner working?

Image Output
===============
Some way to only get base64 encode image, without direct output to browser.

Thanks for your time.

**Comment by ayeo** [comment]
1. Added AIs: 11 and 21
2. Can not recreate the problem. I need more info, full code. My result https://d.pr/i/c77KIh
3. I added getBase64() method to builder
```
$builder->getBase64('(415)7709998021938(8020)0000000583(3900)01243200(96)20170714');
```

**Comment by GrupoWebex** [comment]
I really appreciate your fast response and fix.
Points 1 and 3 was cool. Thanks!

Im testing a lot of gs1-128 codes from internet and i have lost digits on all.
Example from your gs1 code results: 415770999802138802000000058339000124300962017

Maybe is a scanner problem? It's my first day/time testing gs1-128. 
I have test with other codes, and problem persist, lost numbers, so i think i need a new scanner :(

Thanks!

**Comment by ayeo** [comment]
Let me know if you work out something ;)

**Comment by GrupoWebex** [comment]
Hey Ayeo, confirmed was a scanner error, code is working fine. New scanner is working fine on all cases.
Sorry about inconveniences.
