### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by GrupoWebex** [ayeo/gs1_128#14]
Hello, I suggest features:
 - Composer version update
 - Option to disable textlabel, like $builder->setBarcodeLabel(false); 

My hardcoded temp solution
```
//Printer.php
private function prepare($textToEncode)
    {
        $textToEncode = $str=preg_replace('/\s+/', '', $textToEncode);
        $this->imageHandler = imagecreate($this->width, $this->height);
        $this->allocatedBackgroundColor = $this->initColor($this->backgroundColor);
        $this->allocatedPrintColor = $this->initColor($this->printColor);

        $barcode = $this->barsGenerator->generate($textToEncode);

        if ($this->imposedScale)
        {
            $this->scale = $this->imposedScale;
        }
        else
        {
            $this->scale = $this->scaleCalculator->getBarWidth($this->width, $barcode);
        }

        $this->printBars($barcode);
        //$this->printText($textToEncode);
    }


public function setFontSize($fontSize)
    {
        //todo: must be greater than 0
        $this->fontSize = $fontSize;
        //$this->barHeight = $this->height - $this->fontSize - 10;
        $this->barHeight = $this->height;

        if ($this->barHeight < 10)
        {
            throw new RuntimeException('Image is to short');
        }
    }

**Comment by ayeo** [comment]
Hi,

I like your idea with optional label. Thank you for code snippets - I will add this to repo shortly. But I dont know what you mean with suggestion of updating composer version, could you provide me with more details? Thank you for your commitment :D

**Comment by marko-behm** [comment]
Hi, any progress with the option to disable the textlabel?

**Comment by GrupoWebex** [comment]
> Hi, any progress with the option to disable the textlabel?

I don't know, but you can use the code on first post temporally.

**Comment by ayeo** [comment]
Hi, to be honest, I have thoroughly forgotten about that request. Sorry about that. I will try to add that feature asap.

**Comment by GrupoWebex** [comment]
pull requested

**Comment by ayeo** [comment]
Feature of disabling label has been added as 1.0.4 vesion. Check out readme.
