### ISSUE TITLE
AI 403

### ISSUE THREAD

**Issue by patrikdusek** [ayeo/gs1_128#15]
Hi Ayeo,
first of all thanks for your work :)
I'm currently trying to use this barcode-generator for the DHL barcodes (German Parcelservice). I added the 403 to the datalist so I don't get an error for a not supported code. The format for 403 is the same as for 400 but the "Date Title" is different to the 400. The barcodes look slightly different to what I get from DHL so I think there must be more adjusted. Can you please give me a hint what to change. I attached a screenshot. The one in the top is generated by your code the lower one is from DHL.
![difference](https://user-images.githubusercontent.com/819388/93069339-d7cb6f00-f67d-11ea-8de2-c7764566aac9.PNG)

Thx,
Patrik

**Comment by ayeo** [comment]
Hi, I am glad you found this lib useful :) Thank you for your message. It is hard to grasp the problem at first look. I will investigate this today evening and will let you know.

**Comment by ayeo** [comment]
Hi again, I think I've managed to fix that. Let me know if it work for you properly. Make sure you are using 1.0.3 verson. There was a bug in selecting subset strategy. It seems to me that the generated code would be fully readable anyway. But now it should generate exatly same barcode as you provided.

**Comment by patrikdusek** [comment]
Hi Ayeo,
works perfect!!!!! :)
Many thanks,
Patrik
