### ISSUE TITLE
Not usable at all

### ISSUE THREAD

**Issue by legitalk** [ayeo/gs1_128#2]
Impossible to implement, autoload not working at all.

**Comment by javierportillo** [comment]
@legitalk Are you using composer? Please elaborate.

**Comment by ayeo** [comment]
Due to lack of any feedback I close the issue

**Comment by w3l** [comment]
```
$builder = new Barcode\Builder();
$builder->output('(10)123456(400)11');
```

causes `Uncaught Error: Class 'Barcode\Builder' not found` for me,

using the following works with composers autoloader:
```
$builder = new Ayeo\Barcode\Builder();
$builder->output('(10)123456(400)11');
```

Perhaps this was the issue @legitalk had?

**Comment by ayeo** [comment]
You are probably right ;) I've added proper "use" statement in examples. Thank you.
