### ISSUE TITLE
Need an identifier for my barcode

### ISSUE THREAD

**Issue by elinares** [ayeo/gs1_128#3]
Hello!

Great library! after searching in a lot of sites i found this one and is excellent. My barcode includes the identifier 3900 but i can see is not supported for the library. Can you help me with that please?

Here is my barcode string:
(415)7709998418295(8020)7277004113(3900)02144244(96)20170525

Thank you!

**Comment by ayeo** [comment]
Hi,

sure, I will add this at the weekend ;)

**Comment by ayeo** [comment]
Hi,

Requested code has been added ;) Let me know if you need something more. Nonetheless feel free to add some yourself. I would be happy to add your changes  ;)

**Comment by cesarpinzongont** [comment]
Hello!, I Have a problem, I run the code and return this error: Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory, gs1_128-master\index.php on line 6, how can I get autoload.php?

**Comment by elinares** [comment]
Thank you for your help adding identifier, now i have only one question how can i remove the whi spaces around the barcode ¿?

**Comment by ayeo** [comment]
Could you elaborate what exactly you want to achieve?

**Comment by elinares** [comment]
Yes! i need to remove these blank spaces, i've almost achieve that playing with the size of the barcode but always the image return a small blank space around the barcode.

![image](https://user-images.githubusercontent.com/5595552/30602212-2bae9fde-9d21-11e7-856d-7c1bd833b0f6.png)

**Comment by ayeo** [comment]
The problem is that bar width does not allow to fit bar code exactly to given space. Bars must differ to each other by particular percentage value. The simplest way I can imagine is to dont strictly respect size of the image. For example if you set witdht to 150 but generated bar code takes only 138 the result image will be 138px of widht. Does this kind of solution statisfy your needs?

**Comment by elinares** [comment]
Yes, that is what i did to solve the issue. Thanks for your great help!

**Comment by cesarpinzongont** [comment]
Hello again!, I Have a problem, I run the code and return this error: Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory, gs1_128-master\index.php on line 6, how can I get autoload.php?

**Comment by elinares** [comment]
Hello @cesarpinzongont you need to install all dependencies of the project, you can do that with composer.
