### ISSUE TITLE
how can I use or install the library without composer?

### ISSUE THREAD

**Issue by JeisonVM** [ayeo/gs1_128#4]
Hello my friend, I Need to Create a barcode with format:
(415)7709998418295(8020)7277004113(3900)02144244(96)20170525
but I haven't could to use the library widthout composer. how can I use or install the library without composer? 
Please friend, I need to generate the format. Thank you for read.

**Comment by ayeo** [comment]
Hi,

all you need to do is to register the namespace in your autoloader. Let me know if it works to you ;)

**Comment by JasonVM** [comment]
hello, where I can downloar the autoloader and what is the namespaces to register into autoloader?
