### ISSUE TITLE
how Can I use to Library with DOOMPDF or Other?

### ISSUE THREAD

**Issue by JeisonVM** [ayeo/gs1_128#5]
Hello, Thanks, How can I use my barcode into the PDF? Thank for response.

**Comment by ayeo** [comment]
Hi,

the easiest way in my opinion is to generate png with the code an simply attach/include it into your pdf file

**Comment by JeisonVM** [comment]
Oh thanks, How can I to delete of textnUmber in the image barcode? ¿it is Posible?
I try  $builder->output('(415)1502443400203(8020)201415\x1D(3900)050000\x1D(96)20170628');
This \x1D is GS ASCCI but I don't want to show in the barcode.

**Comment by ayeo** [comment]
Hi,

The best you can do is to add new setting determining if text should be added or not. If you are looking for ad hoc solution just comment line 136 (http://d.pr/i/REvfQ) in Printer.php file

**Comment by carlos-andres** [comment]
@JasonVM Good Day.. did you resolver the barcode.. is possible for you share the code?
