### ISSUE TITLE
how can i install in Laravel 5.*?

### ISSUE THREAD

**Issue by WookPlay** [ayeo/gs1_128#6]
I would like the steps to be taken if I want to install in laravel 5. *

**Comment by ayeo** [comment]
Hi, I dont know much about laravel 5. But as far as I can tell all you need to do is to add this lib to your composer dependencies.

**Comment by WookPlay** [comment]
@ayeo  Add the class to the composer but when executing it, it does not display the barcode: /

**Comment by WookPlay** [comment]
@ayeo  I already solve it, Thanks.
In the following way:
```
$ cod = '(415) 7707242745227 (8020) 170913100114 (3900) 000000000038500 (96) 20170919';
$ img = $ builder-> output ($ cod);
return response ($ img) -> header ('Content-type', 'image / png');
```

**Comment by ayeo** [comment]
Glad to hear that ;) Can we close the issue then?
