### ISSUE TITLE
How can I return bar code in data: base64?

### ISSUE THREAD

**Issue by WookPlay** [ayeo/gs1_128#7]
Hi, I wanted to know if I can return the barcode img as data: base64.

**Comment by ayeo** [comment]
Hi, I just have added method for that Printer::getBase64($textToEncode). Check out if this work for you.

I have added some [tests](https://github.com/ayeo/gs1_128/blob/master/tests/PrinterTest.php) using your barcode (415) 7707242745227 (8020) 170913100114 (3900) 000000000038500 (96) 20170919.
This has revealed some problem with whitespaces - should be fine now.

**Comment by WookPlay** [comment]
Thanks
