### ISSUE TITLE
Empty response.. 

### ISSUE THREAD

**Issue by carlos-andres** [ayeo/gs1_128#8]
Good day.. i use the sample code.. and withor without content type the result image is empty

` header('Content-Type: image/png');  `

  i´m use php 7.1 btw

<img width="547" alt="screen shot 2019-01-27 at 3 20 27 pm" src="https://user-images.githubusercontent.com/5489747/51806365-24fb9280-2247-11e9-9069-c2988c1c5f47.png">

**Comment by ayeo** [comment]
Hi,

I will check it out today ;)

**Comment by ayeo** [comment]
Hi,

I can't reproduce the issue. What I've done is:

1. ```docker run -p 80:80 -v $(pwd):/var/www/html -d richarvey/nginx-php-fpm```
2. visit ```http://localhost:80```
3. result: https://d.pr/i/B9OaBS

Everything looks fine, given image uses 7.2. Default index.php contains same code as readme.md file. Can you try this or paste your full source?

**Comment by ayeo** [comment]
Did you run ```composer install```?

**Comment by carlos-andres** [comment]
Good day thanks for your answer. 

sure, you can check short video 

https://drive.google.com/open?id=16cs84LbxyusKlpuiL_aayw6ot-G1WREu

**Comment by ayeo** [comment]
Thank you for detailed feedback. I've spend some time trying reproduce the issue but with no success. I tried same PHP version as you (7.1.25) and still get valid result. I also wonder why your page background is black, it shouldnt. The best you can do is to debug the issue on your own. Set your php env as follows:

```
ini_set('display_errors', true);
error_reporting(E_ALL);
```

then comment headers in Response.php

```
public function output($text, $filename, $disposition = 'inline')
    {
        //header(sprintf('Content-Type: %s', $this->getType()));
        //header(sprintf('Content-Disposition: %s;filename=%s', $disposition, $filename));
        imagepng($this->printer->getResource($text));
    }

```

Now you probably get the exact error that occurs. Let me know what you'll find out.

**Comment by carlos-andres** [comment]
Good day.. i see now the issue.. let me copy result code.. and thanks again for your support

![image](https://user-images.githubusercontent.com/5489747/51849877-9cd0c800-22ee-11e9-9dc1-566fd63b55b5.png)



` <br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function Ayeo\Barcode\imagettftext() in /Users/{user}/Sites/gs1/src/Printer.php:242
Stack trace:
#0 /Users/{user}/Sites/gs1/src/Printer.php(133): Ayeo\Barcode\Printer-&gt;printText('(10)123456(400)...')
#1 /Users/{user}/Sites/gs1/src/Printer.php(154): Ayeo\Barcode\Printer-&gt;prepare('(10)123456(400)...')
#2 /Users/{user}/Sites/gs1/src/Response/Response.php(19): Ayeo\Barcode\Printer-&gt;getResource('(10)123456(400)...')
#3 /Users/{user}/Sites/gs1/src/Builder.php(76): Ayeo\Barcode\Response\Response-&gt;output('(10)123456(400)...', 'barcode.jpg')
#4 /Users/{user}/Sites/gs1/index.php(22): Ayeo\Barcode\Builder-&gt;output('(10)123456(400)...')
#5 {main}
  thrown in <b>/Users/{user}/Sites/gs1/src/Printer.php</b> on line <b>242</b><br /> `

**Comment by ayeo** [comment]
According to php manual imgagetftext requires both GD and  FreeType library. You need add  FreeType to your php I am afraid. I will add those requirements to composer.json so next time you will get clear message while running ```composer install```

Thank you for the report ;)

**Comment by carlos-andres** [comment]
it´s tricky because i´ve freetype installed

![image](https://user-images.githubusercontent.com/5489747/51850814-8af02480-22f0-11e9-8c73-c2a58a5edd74.png)

But not linked on the php.. so now it´s working thanks.

**Comment by ayeo** [comment]
Thank you for the feedback ;)
