### ISSUE TITLE
Check digit (Function Code 1 (FNC1))

### ISSUE THREAD

**Issue by Atnaize** [ayeo/gs1_128#9]
As described in [this page](https://www.gs1-128.info/), is it possible to generate the check digit with this package?

I didn't figured out how to use it.
I see that you have a `src/Data/BinaryMap.php`, so I guess it should be possible?

My code should be like this
`(01) 5 4005500 00199 X (13) 171025 (10) 2017102511`

X being the check digit, a `2` in this example

**Comment by ayeo** [comment]
Hi Atnaize,

the library was intended as gs1-128 bar code printer. There is another my library that may turn out handy for you:

https://github.com/ayeo/gs1/blob/master/src/Utils/CheckDigitCalculator.php

**Comment by Atnaize** [comment]
Thank you! I'll try this out asap!
